### ISSUE TITLE
Ocean :: Dimitra Data Challenge

### ISSUE THREAD

**Issue by OceanRaymond** [trangnv/Ocean-Protocol---Dimitra-Bounty-Phase-2#1]
Hi, Trang! This is Ray from Ocean Protocol. You have a won prize in the Dimitra Data Challenge. However, I don't have your email address to continue the process. Please contact me at raymond@oceanprotocol.com Thanks!

**Comment by trangnv** [comment]
Hi Ray,
I sent you an email.
Thanks
